@startuml HL_Jeans
left to right direction
skinparam packageStyle rectangle
skinparam actorStyle awesome
skinparam shadowing false
skinparam usecase {
  BackgroundColor #EFEFEF
  BorderColor #2D3E50
  ArrowColor #2D3E50
}

actor "Cliente" as Cliente
actor "Administrador" as Admin

rectangle "HL Jeans" {
    
    ' Funcionalidades centrais
    (Fazer login) as Login
    (Listar produtos) as Listar
    
    ' Funcionalidades do Cliente
    (Cadastrar-se) as Cadastrar
    (Pesquisar produto) as Pesquisar
    (Adicionar produto ao carrinho) as AdicionarCarrinho
    (Visualizar carrinho) as VerCarrinho
    (Finalizar compra) as FinalizarCompra
    (Exibir resumo do pedido) as ExibirResumo
}

' --- Relacionamentos do Cliente ---
Cliente --> Cadastrar
Cliente --> Login
Cliente --> Listar
Cliente --> Pesquisar
Cliente --> AdicionarCarrinho
Cliente --> VerCarrinho
Cliente --> FinalizarCompra

' --- Relacionamentos do Administrador ---
Admin --> Login
Admin --> Listar 

' --- Relações de Inclusão (<<inclui>>) ---
' Para adicionar, o sistema *sempre* inclui a pesquisa
(AdicionarCarrinho) ..> (Pesquisar) : <<inclui>>

' Para finalizar, o sistema *sempre* exibe o resumo e limpa o carrinho
(FinalizarCompra) ..> (ExibirResumo) : <<inclui>>

@enduml
